apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zp5bd97c4-java-springboot
  janus-idp.io/tekton: zp5bd97c4-java-springboot
  backstage.io/kubernetes-id: zp5bd97c4-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zp5bd97c4-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
